# @package _group_
_target_: engine.engineCaloV3.EngineCaloV3
learning_rate: 0.0001
n_train_batch_size: 100
n_test_batch_size: 1024
n_valid_batch_size: 1024
n_plot_samples: 10
n_batches_log_train: 100
n_epochs: 1
n_gibbs_sampling_steps: 50
weight_decay_factor: 0.0001
momentum_coefficient: 0.5
kl_enabled: 1
kl_annealing: 1
kl_annealing_ratio: 0.3
ae_enabled: 1
sample_energies:
  - 1
  - 25
  - 50
  - 100
  - 150