
model_type: cVAE
activation_fct: RELU
encoder_hidden_nodes: 
  - 512
  - 256
  - 256
  - 128
decoder_hidden_nodes: 
  - 128 
  - 256 
  - 256 
  - 512
n_latent_nodes: 16
#for generation task
target_numbers: 
  - 0 
  - 1 
  - 2