model_type: GumBoltCaloCRBM
activation_fct: relu
beta_smoothing_fct: 5
output_smoothing_fct: 9
decoder_hidden_nodes:
  - 800
  - 700
  - 600
  - 550
encoder_hidden_nodes:
  - 500
  - 450
  - 400
  - 350
  - 300
n_latent_hierarchy_lvls: 6
n_latent_nodes: 150

n_encoder_layer_nodes: -1
n_encoder_layers: -1