# @package _group_
tag: default
debug: False
load_data_from_pkl: 0
load_model: 0
input_model: 
  # ./output/divae_mnist/model_DiVAE_mnist_1200_100_400_2_0.001_4_100_tanh_default_210126.pt
output_path: ???

defaults:
  - model: sequentialVAE
  - data: calo
  - engine: calo_training
  - task